import { Styles } from "console-feed/lib/definitions/Styles";

export const consoleTheme: Styles = {
  // Common Style
  LOG_BACKGROUND: "#242424",
  LOG_BORDER: "#282828",

  OBJECT_VALUE_STRING_COLOR: "#1EAAF1",
  OBJECT_VALUE_NUMBER_COLOR: "#F8DFAF",
  OBJECT_VALUE_BOOLEAN_COLOR: "#F8DFAF",
  OBJECT_VALUE_UNDEFINED_COLOR: "#6E6E6E",
  OBJECT_VALUE_NULL_COLOR: "#6E6E6E",
  OBJECT_NAME_COLOR: "#93C96A",
  OBJECT_VALUE_SYMBOL_COLOR: "#A3806E",
  OBJECT_VALUE_FUNCTION_KEYWORD_COLOR: "#D87075",

  LOG_WARN_BACKGROUND: "#332B01",
  BASE_BACKGROUND_COLOR: "rgba(0,0,0,0)",
};
